apiVersion: apps/v1
kind: Deployment
metadata:
  name: aquarium-admin-test
spec:
  selector:
    matchLabels:
      app: aquarium-admin
      environment: test
  template:
    metadata:
      labels:
        app: aquarium-admin
        environment: test
    spec:
      containers:
        - name: aquarium-admin-test
          image: ayase-252/aquarium-admin:master
          ports:
            - containerPort: 5000
          env:
            - name: MODE
              value: test
---
apiVersion: v1
kind: Service
metadata:
  name: aquarium-admin-test
spec:
  selector:
    app: aquarium-admin
    environment: test
  ports:
    - port: 80
      targetPort: 4000
